name: reporthax

on: 
  workflow_dispatch:
    inputs:
      tunnel:
        required: true
      assetid:
        required: true
        
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Starting Report
      run: ./start.ps1 ${{github.run_id}} ${{github.event.inputs.tunnel}} ${{github.event.inputs.assetid}}
